site_name: Discography

#use_directory_urls: false

theme:
  name: mkdocs

copyright: 'Copyright &copy; 2026 Primo Studios / George Senger.<br/>All rights reserved.'

extra_css:
  - stylesheets/dsc.css

nav:
  - Home: index.md
  - User Guide:
      - User Interface: ui.md
      - Managing Your Collection: collection.md
      - Searching Your Collection: search.md
      - MusicBrainz Integration: musicbrainz.md
      - Advanced Features: advanced.md
